name: lingzhi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - ffmpeg
  - libopus
  - pip:
    - fastapi>=0.104.1
    - uvicorn>=0.24.0
    - pydantic>=2.5.1
    - python-multipart>=0.0.6
    - websockets==14.2
    - PyYAML>=6.0.1
    - edge-tts>=7.0.0
    - opuslib_next==1.1.2
    - torch==2.2.2
    - pyyml==0.0.2
    - silero_vad==5.1.2
    - pydub==0.25.1
    - funasr==1.2.3
    - torchaudio==2.2.2
    - openai==1.61.0
    - google-generativeai==0.8.4
    - edge_tts==7.0.0
    - httpx==0.27.2
    - aiohttp==3.9.3
    - aiohttp_cors==0.7.0
    - ormsgpack==1.7.0
    - ruamel.yaml==0.18.10
    - loguru==0.7.3
    - requests>=2.0.0
